// File generated by params.SaveGoCode

package main

import "github.com/emer/emergent/params"

// SavedParamsSets is currently the default place hip_pairs looks for param values
var SavedParamsSets = params.Sets{
	{Name: "Base", Desc: "these are the best params", Sheets: params.Sheets{
		"Network": &params.Sheet{
			{Sel: "Prjn", Desc: "keeping default params for generic prjns",
				Params: params.Params{
					"Prjn.Learn.Momentum.On": "true",
					"Prjn.Learn.Norm.On":     "true",
					"Prjn.Learn.WtBal.On":    "false",
				}},
			{Sel: ".EcCa1Prjn", Desc: "encoder projections -- no norm, moment",
				Params: params.Params{
					"Prjn.Learn.Lrate":       "0.05",
					"Prjn.Learn.Momentum.On": "false",
					"Prjn.Learn.Norm.On":     "false",
					"Prjn.Learn.WtBal.On":    "false",
				}},
			{Sel: ".HippoCHL", Desc: "hippo CHL projections -- no norm, moment, but YES wtbal = sig better",
				Params: params.Params{
					"Prjn.CHL.Hebb":          "0.05",
					"Prjn.Learn.Lrate":       "0.4",
					"Prjn.Learn.Momentum.On": "false",
					"Prjn.Learn.Norm.On":     "false",
					"Prjn.Learn.WtBal.On":    "true",
				}},
			{Sel: "#ECinToCA1", Desc: "New ECin to CA1 params for paper matching",
				Params: params.Params{
					"Prjn.WtScale.Abs":       "3.0",
					"Prjn.WtScale.Rel":       "1",
					"Prjn.WtInit.Mean":       "0.5",
					"Prjn.WtInit.Var":        "0.25",
					"Prjn.Learn.Lrate":       "0.05",
					"Prjn.Learn.Norm.On":     "true",
					"Prjn.Learn.Momentum.On": "true",
				}},
			{Sel: "#ECinToDG", Desc: "New ECin to DG params for paper matching",
				Params: params.Params{
					"Prjn.WtScale.Abs":           "1",
					"Prjn.WtScale.Rel":           "1",
					"Prjn.WtInit.Mean":           "0.5",
					"Prjn.WtInit.Var":            "0.25",
					"Prjn.Learn.Lrate":           "0.4",
					"Prjn.Learn.Norm.On":         "true",
					"Prjn.Learn.Momentum.On":     "true",
					"Prjn.CHL.Hebb":              "0.001",
					"Prjn.CHL.Err":               "0.999",
					"Prjn.Learn.WtSig.SoftBound": "true",
				}},
			{Sel: "#ECinToCA3", Desc: "New ECin to CA3 params for paper matching",
				Params: params.Params{
					"Prjn.WtScale.Abs": "1",
					"Prjn.WtScale.Rel": "1",
					"Prjn.WtInit.Mean": "0.5",
					"Prjn.WtInit.Var":  "0.25",
					"Prjn.Learn.Lrate": "0.4",
				}},
			{Sel: "#CA1ToECout", Desc: "extra strong from CA1 to ECout",
				Params: params.Params{
					"Prjn.WtScale.Abs":       "1.0",
					"Prjn.WtScale.Rel":       "1.0",
					"Prjn.Learn.Lrate":       "0.05",
					"Prjn.WtInit.Mean":       "0.5",
					"Prjn.WtInit.Var":        "0.25",
					"Prjn.Learn.Norm.On":     "true",
					"Prjn.Learn.Momentum.On": "true",
				}},
			{Sel: "#InputToECin", Desc: "one-to-one input to EC",
				Params: params.Params{
					"Prjn.Learn.Learn": "false",
					"Prjn.WtInit.Mean": "0.5",
					"Prjn.WtInit.Var":  "0.0",
					"Prjn.WtScale.Abs": "1",
					"Prjn.WtScale.Rel": "1",
				}},
			{Sel: "#ECoutToCA1", Desc: "new params for ECout to CA1 to match paper",
				Params: params.Params{
					"Prjn.Learn.Learn":       "true",
					"Prjn.Learn.Lrate":       "0.05",
					"Prjn.WtInit.Mean":       "0.5",
					"Prjn.WtInit.Var":        "0.25",
					"Prjn.WtScale.Abs":       "1.0",
					"Prjn.WtScale.Rel":       "1.0",
					"Prjn.Learn.Norm.On":     "true",
					"Prjn.Learn.Momentum.On": "true",
				}},
			{Sel: "#ECoutToECin", Desc: "one-to-one out to in",
				Params: params.Params{
					//DS: wtscale.abs changed to match paper and changes back to default
					"Prjn.Learn.Learn": "false",
					"Prjn.WtInit.Mean": "0.5",
					"Prjn.WtInit.Var":  "0.0",
					"Prjn.WtScale.Abs": "2.0",
					"Prjn.WtScale.Rel": "0.5",
				}},
			{Sel: "#DGToCA3", Desc: "Mossy fibers: strong, non-learning",
				Params: params.Params{
					"Prjn.CHL.Hebb":              "0.001",
					"Prjn.CHL.SAvgCor":           "0.6",
					"Prjn.Learn.Learn":           "false",
					"Prjn.WtInit.Mean":           "0.9",
					"Prjn.WtInit.Var":            "0.01",
					"Prjn.WtScale.Abs":           "1.0",
					"Prjn.WtScale.Rel":           "8",
					"Prjn.Learn.Norm.On":         "true",
					"Prjn.Learn.Momentum.On":     "true",
					"Prjn.Learn.WtSig.SoftBound": "true",
				}},
			{Sel: "#CA3ToCA3", Desc: "CA3 recurrent cons",
				Params: params.Params{
					"Prjn.CHL.Hebb":              "0.001",
					"Prjn.CHL.SAvgCor":           "0.6",
					"Prjn.WtScale.Abs":           "1.0",
					"Prjn.WtScale.Rel":           "1.0",
					"Prjn.WtInit.Mean":           "0.5",
					"Prjn.WtInit.Var":            "0.25",
					"Prjn.Learn.Lrate":           "0.4",
					"Prjn.Learn.Norm.On":         "true",
					"Prjn.Learn.Momentum.On":     "true",
					"Prjn.Learn.WtSig.SoftBound": "true",
					"Prjn.CHL.Err":               "0.999",
				}},
			{Sel: "#CA3ToCA1", Desc: "Schaffer collaterals -- slower, less hebb",
				Params: params.Params{
					"Prjn.CHL.Hebb":              "0.001",
					"Prjn.CHL.SAvgCor":           "0.4",
					"Prjn.Learn.Lrate":           "0.05",
					"Prjn.WtInit.Mean":           "0.5",
					"Prjn.WtInit.Var":            "0.25",
					"Prjn.WtScale.Abs":           "1.0",
					"Prjn.WtScale.Rel":           "1.0",
					"Prjn.Learn.Norm.On":         "true",
					"Prjn.Learn.Momentum.On":     "true",
					"Prjn.Learn.WtSig.SoftBound": "true",
					"Prjn.CHL.Err":               "0.999",
				}},
			{Sel: ".EC", Desc: "all EC layers: only pools, no layer-level",
				Params: params.Params{
					"Layer.Act.Gbar.L":        ".1",
					"Layer.Inhib.ActAvg.Init": "0.2",
					"Layer.Inhib.Layer.On":    "true",
					"Layer.Inhib.Layer.Gi":    "1.8",
				}},
			{Sel: "#DG", Desc: "very sparse = high inibhition",
				Params: params.Params{
					"Layer.Inhib.ActAvg.Init": "0.01",
					"Layer.Inhib.Layer.Gi":    "21",
					"Layer.Act.Gbar.L":        ".2",
				}},
			{Sel: "#CA3", Desc: "sparse = high inibhition",
				Params: params.Params{
					"Layer.Inhib.ActAvg.Init": "0.02",
					"Layer.Inhib.Layer.Gi":    "4.5",
					"Layer.Act.Gbar.L":        ".2",
				}},
			{Sel: "#CA1", Desc: "CA1 only Pools",
				Params: params.Params{
					"Layer.Inhib.ActAvg.Init": "0.1",
					"Layer.Inhib.Layer.On":    "true",
					"Layer.Inhib.Layer.Gi":    "1.7",
					"Layer.Act.Gbar.L":        ".2",
				}},
		},
		"Sim": &params.Sheet{
			{Sel: "Sim", Desc: "best params always finish in this time",
				Params: params.Params{
					"Sim.MaxEpcs": "10",
					//"Sim.MaxRuns": "1",
				}},
		},
	}},
	{Name: "NoCHL", Desc: "no learning in CHL main hip pathways -- for debugging auto-encoder", Sheets: params.Sheets{
		"Network": &params.Sheet{
			{Sel: ".HippoCHL", Desc: "no learning",
				Params: params.Params{
					"Prjn.Learn.Lrate": "0",
				}},
		},
		"Sim": &params.Sheet{},
	}},
	{Name: "CHLWtBal", Desc: "CHL uses weight baance -- much better -- now in base", Sheets: params.Sheets{
		"Network": &params.Sheet{
			{Sel: ".HippoCHL", Desc: "wtbal on",
				Params: params.Params{
					"Prjn.Learn.WtBal.On": "true",
				}},
		},
		"Sim": &params.Sheet{},
	}},
	{Name: "EncWtBal", Desc: "encoder uses weight balance -- worse", Sheets: params.Sheets{
		"Network": &params.Sheet{
			{Sel: ".EcCa1Prjn", Desc: "wtbal on",
				Params: params.Params{
					"Prjn.Learn.WtBal.On": "true",
				}},
		},
		"Sim": &params.Sheet{},
	}},
	{Name: "EncMom", Desc: "encoder uses momentum -- worse", Sheets: params.Sheets{
		"Network": &params.Sheet{
			{Sel: ".EcCa1Prjn", Desc: "moment on",
				Params: params.Params{
					"Prjn.Learn.Momentum.On": "true",
					"Prjn.Learn.Norm.On":     "true",
				}},
		},
		"Sim": &params.Sheet{},
	}},
	{Name: "AllWtBal", Desc: "All use weight balance", Sheets: params.Sheets{
		"Network": &params.Sheet{
			{Sel: ".HippoCHL", Desc: "wtbal on",
				Params: params.Params{
					"Prjn.Learn.WtBal.On": "true",
				}},
			{Sel: ".EcCa1Prjn", Desc: "wtbal on",
				Params: params.Params{
					"Prjn.Learn.WtBal.On": "true",
				}},
		},
		"Sim": &params.Sheet{},
	}},
}
